---
- name: Configure all k8s nodes
  hosts: all
  become: true
  roles:
    - common

- name: Initialize control plane
  hosts: controlplane
  become: true
  roles:
    - controlplane

- name: Join worker nodes
  hosts: workers
  become: true
  roles:
    - worker
